language: node_js
node_js:
- 10
before_install:
- openssl aes-256-cbc -K $encrypted_703b0bee0b5e_key -iv $encrypted_703b0bee0b5e_iv
  -in credentials.json.enc -out ./constants/credentials.json -d
- openssl aes-256-cbc -K $encrypted_703b0bee0b5e_key -iv $encrypted_703b0bee0b5e_iv
  -in app-engine-secrets.json.enc -out ./app-engine-secrets.json -d
- gcloud auth activate-service-account --key-file client-secret.json
install:
- gcloud config set project authorization-server-261201
before_script:
- npm install
script:
- npm run test && gcloud -q app deploy app.yaml --promote --version 1-0-0
